apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  labels:
    app: fastapi
data: 
  URL : cG9zdGdyZXNxbDovL2Zhc3RhcGlfdXNlcjpmYXN0YXBpX3Bhc3N3ZEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvZmFzdGFwaV9kYg==
